<?xml version="1.0" encoding="utf-8"?><Database Name="biblioteca" Class="OperacionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=biblioteca;User ID=usuarioSQL" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bibliotecaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tematicas" Member="tematicas">
    <Type Name="tematicas">
      <Column Name="codtema" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tema" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="tematicas_libros" Member="libros" ThisKey="codtema" OtherKey="codtema" Type="libros" />
    </Type>
  </Table>
  <Table Name="dbo.prestamos" Member="prestamos">
    <Type Name="prestamos">
      <Column Name="codprestamo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codejemplar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechaprestamo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fechadevolucion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecharealdevo" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="codalumno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="ejemplares_prestamos" Member="ejemplares" ThisKey="codejemplar" OtherKey="codejemplar" Type="ejemplares" IsForeignKey="true" />
      <Association Name="alumnos_prestamos" Member="alumnos" ThisKey="codalumno" OtherKey="codalumno" Type="alumnos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.libros" Member="libros">
    <Type Name="libros">
      <Column Name="codlibro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="codtema" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codeditorial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codidioma" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="donado" Type="System.Char" DbType="Char(1)" CanBeNull="false" />
      <Association Name="libros_ejemplares" Member="ejemplares" ThisKey="codlibro" OtherKey="codlibro" Type="ejemplares" />
      <Association Name="libros_autorexlibro1" Member="autorexlibro" ThisKey="codlibro" OtherKey="codlibro" Type="autorexlibro" />
      <Association Name="tematicas_libros" Member="tematicas" ThisKey="codtema" OtherKey="codtema" Type="tematicas" IsForeignKey="true" />
      <Association Name="idiomas_libros" Member="idiomas" ThisKey="codidioma" OtherKey="codidioma" Type="idiomas" IsForeignKey="true" />
      <Association Name="editoriales_libros" Member="editoriales" ThisKey="codeditorial" OtherKey="codeditorial" Type="editoriales" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.idiomas" Member="idiomas">
    <Type Name="idiomas">
      <Column Name="codidioma" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idioma" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="idiomas_libros" Member="libros" ThisKey="codidioma" OtherKey="codidioma" Type="libros" />
    </Type>
  </Table>
  <Table Name="dbo.estados" Member="estados">
    <Type Name="estados">
      <Column Name="codestado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="estados_ejemplares" Member="ejemplares" ThisKey="codestado" OtherKey="codestado" Type="ejemplares" />
    </Type>
  </Table>
  <Table Name="dbo.ejemplares" Member="ejemplares">
    <Type Name="ejemplares">
      <Column Name="codejemplar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codestado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codlibro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ejemplares_prestamos" Member="prestamos" ThisKey="codejemplar" OtherKey="codejemplar" Type="prestamos" />
      <Association Name="estados_ejemplares" Member="estados" ThisKey="codestado" OtherKey="codestado" Type="estados" IsForeignKey="true" />
      <Association Name="libros_ejemplares" Member="libros" ThisKey="codlibro" OtherKey="codlibro" Type="libros" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.editoriales" Member="editoriales">
    <Type Name="editoriales">
      <Column Name="codeditorial" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="editorial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="editoriales_libros" Member="libros" ThisKey="codeditorial" OtherKey="codeditorial" Type="libros" />
    </Type>
  </Table>
  <Table Name="dbo.autores" Member="autores">
    <Type Name="autores">
      <Column Name="codautor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="autor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="autores_autorexlibro1" Member="autorexlibro" ThisKey="codautor" OtherKey="codautor" Type="autorexlibro" />
    </Type>
  </Table>
  <Table Name="dbo.alumnos" Member="alumnos">
    <Type Name="alumnos">
      <Column Name="codalumno" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="numPrestados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="alumnos_prestamos" Member="prestamos" ThisKey="codalumno" OtherKey="codalumno" Type="prestamos" />
    </Type>
  </Table>
  <Table Name="dbo.autorexlibro" Member="autorexlibro">
    <Type Name="autorexlibro">
      <Column Name="codlibro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codautor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="autorxlibro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="autores_autorexlibro1" Member="autores" ThisKey="codautor" OtherKey="codautor" Type="autores" IsForeignKey="true" />
      <Association Name="libros_autorexlibro1" Member="libros" ThisKey="codlibro" OtherKey="codlibro" Type="libros" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.aloha" Method="aloha">
    <ElementType Name="alohaResult">
      <Column Name="codalumno" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="numPrestados" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.insertarAutorxLibro" Method="insertarAutorxLibro">
    <Parameter Name="libro" Type="System.Int32" DbType="Int" />
    <Parameter Name="autor" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>