#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_Ejemplo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="biblioteca")]
	public partial class OperacionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttematicas(tematicas instance);
    partial void Updatetematicas(tematicas instance);
    partial void Deletetematicas(tematicas instance);
    partial void Insertprestamos(prestamos instance);
    partial void Updateprestamos(prestamos instance);
    partial void Deleteprestamos(prestamos instance);
    partial void Insertlibros(libros instance);
    partial void Updatelibros(libros instance);
    partial void Deletelibros(libros instance);
    partial void Insertidiomas(idiomas instance);
    partial void Updateidiomas(idiomas instance);
    partial void Deleteidiomas(idiomas instance);
    partial void Insertestados(estados instance);
    partial void Updateestados(estados instance);
    partial void Deleteestados(estados instance);
    partial void Insertejemplares(ejemplares instance);
    partial void Updateejemplares(ejemplares instance);
    partial void Deleteejemplares(ejemplares instance);
    partial void Inserteditoriales(editoriales instance);
    partial void Updateeditoriales(editoriales instance);
    partial void Deleteeditoriales(editoriales instance);
    partial void Insertautores(autores instance);
    partial void Updateautores(autores instance);
    partial void Deleteautores(autores instance);
    partial void Insertalumnos(alumnos instance);
    partial void Updatealumnos(alumnos instance);
    partial void Deletealumnos(alumnos instance);
    #endregion
		
		public OperacionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bibliotecaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OperacionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperacionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperacionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OperacionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tematicas> tematicas
		{
			get
			{
				return this.GetTable<tematicas>();
			}
		}
		
		public System.Data.Linq.Table<prestamos> prestamos
		{
			get
			{
				return this.GetTable<prestamos>();
			}
		}
		
		public System.Data.Linq.Table<libros> libros
		{
			get
			{
				return this.GetTable<libros>();
			}
		}
		
		public System.Data.Linq.Table<idiomas> idiomas
		{
			get
			{
				return this.GetTable<idiomas>();
			}
		}
		
		public System.Data.Linq.Table<estados> estados
		{
			get
			{
				return this.GetTable<estados>();
			}
		}
		
		public System.Data.Linq.Table<ejemplares> ejemplares
		{
			get
			{
				return this.GetTable<ejemplares>();
			}
		}
		
		public System.Data.Linq.Table<editoriales> editoriales
		{
			get
			{
				return this.GetTable<editoriales>();
			}
		}
		
		public System.Data.Linq.Table<autores> autores
		{
			get
			{
				return this.GetTable<autores>();
			}
		}
		
		public System.Data.Linq.Table<alumnos> alumnos
		{
			get
			{
				return this.GetTable<alumnos>();
			}
		}
		
		public System.Data.Linq.Table<autorexlibro> autorexlibro
		{
			get
			{
				return this.GetTable<autorexlibro>();
			}
		}
		
		public System.Data.Linq.Table<VistaxAutores> VistaxAutores
		{
			get
			{
				return this.GetTable<VistaxAutores>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarAutorxLibro")]
		public int insertarAutorxLibro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> libro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> autor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), libro, autor);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tematicas")]
	public partial class tematicas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codtema;
		
		private string _tema;
		
		private EntitySet<libros> _libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodtemaChanging(int value);
    partial void OncodtemaChanged();
    partial void OntemaChanging(string value);
    partial void OntemaChanged();
    #endregion
		
		public tematicas()
		{
			this._libros = new EntitySet<libros>(new Action<libros>(this.attach_libros), new Action<libros>(this.detach_libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codtema", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codtema
		{
			get
			{
				return this._codtema;
			}
			set
			{
				if ((this._codtema != value))
				{
					this.OncodtemaChanging(value);
					this.SendPropertyChanging();
					this._codtema = value;
					this.SendPropertyChanged("codtema");
					this.OncodtemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tema", DbType="VarChar(150)")]
		public string tema
		{
			get
			{
				return this._tema;
			}
			set
			{
				if ((this._tema != value))
				{
					this.OntemaChanging(value);
					this.SendPropertyChanging();
					this._tema = value;
					this.SendPropertyChanged("tema");
					this.OntemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tematicas_libros", Storage="_libros", ThisKey="codtema", OtherKey="codtema")]
		public EntitySet<libros> libros
		{
			get
			{
				return this._libros;
			}
			set
			{
				this._libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.tematicas = this;
		}
		
		private void detach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.tematicas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prestamos")]
	public partial class prestamos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codprestamo;
		
		private System.Nullable<int> _codejemplar;
		
		private System.Nullable<System.DateTime> _fechaprestamo;
		
		private System.Nullable<System.DateTime> _fechadevolucion;
		
		private System.Nullable<System.DateTime> _fecharealdevo;
		
		private string _codalumno;
		
		private EntityRef<ejemplares> _ejemplares;
		
		private EntityRef<alumnos> _alumnos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodprestamoChanging(int value);
    partial void OncodprestamoChanged();
    partial void OncodejemplarChanging(System.Nullable<int> value);
    partial void OncodejemplarChanged();
    partial void OnfechaprestamoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaprestamoChanged();
    partial void OnfechadevolucionChanging(System.Nullable<System.DateTime> value);
    partial void OnfechadevolucionChanged();
    partial void OnfecharealdevoChanging(System.Nullable<System.DateTime> value);
    partial void OnfecharealdevoChanged();
    partial void OncodalumnoChanging(string value);
    partial void OncodalumnoChanged();
    #endregion
		
		public prestamos()
		{
			this._ejemplares = default(EntityRef<ejemplares>);
			this._alumnos = default(EntityRef<alumnos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codprestamo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codprestamo
		{
			get
			{
				return this._codprestamo;
			}
			set
			{
				if ((this._codprestamo != value))
				{
					this.OncodprestamoChanging(value);
					this.SendPropertyChanging();
					this._codprestamo = value;
					this.SendPropertyChanged("codprestamo");
					this.OncodprestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codejemplar", DbType="Int")]
		public System.Nullable<int> codejemplar
		{
			get
			{
				return this._codejemplar;
			}
			set
			{
				if ((this._codejemplar != value))
				{
					if (this._ejemplares.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodejemplarChanging(value);
					this.SendPropertyChanging();
					this._codejemplar = value;
					this.SendPropertyChanged("codejemplar");
					this.OncodejemplarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaprestamo", DbType="Date")]
		public System.Nullable<System.DateTime> fechaprestamo
		{
			get
			{
				return this._fechaprestamo;
			}
			set
			{
				if ((this._fechaprestamo != value))
				{
					this.OnfechaprestamoChanging(value);
					this.SendPropertyChanging();
					this._fechaprestamo = value;
					this.SendPropertyChanged("fechaprestamo");
					this.OnfechaprestamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechadevolucion", DbType="Date")]
		public System.Nullable<System.DateTime> fechadevolucion
		{
			get
			{
				return this._fechadevolucion;
			}
			set
			{
				if ((this._fechadevolucion != value))
				{
					this.OnfechadevolucionChanging(value);
					this.SendPropertyChanging();
					this._fechadevolucion = value;
					this.SendPropertyChanged("fechadevolucion");
					this.OnfechadevolucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecharealdevo", DbType="Date")]
		public System.Nullable<System.DateTime> fecharealdevo
		{
			get
			{
				return this._fecharealdevo;
			}
			set
			{
				if ((this._fecharealdevo != value))
				{
					this.OnfecharealdevoChanging(value);
					this.SendPropertyChanging();
					this._fecharealdevo = value;
					this.SendPropertyChanged("fecharealdevo");
					this.OnfecharealdevoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codalumno", DbType="VarChar(10)")]
		public string codalumno
		{
			get
			{
				return this._codalumno;
			}
			set
			{
				if ((this._codalumno != value))
				{
					if (this._alumnos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodalumnoChanging(value);
					this.SendPropertyChanging();
					this._codalumno = value;
					this.SendPropertyChanged("codalumno");
					this.OncodalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ejemplares_prestamos", Storage="_ejemplares", ThisKey="codejemplar", OtherKey="codejemplar", IsForeignKey=true)]
		public ejemplares ejemplares
		{
			get
			{
				return this._ejemplares.Entity;
			}
			set
			{
				ejemplares previousValue = this._ejemplares.Entity;
				if (((previousValue != value) 
							|| (this._ejemplares.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ejemplares.Entity = null;
						previousValue.prestamos.Remove(this);
					}
					this._ejemplares.Entity = value;
					if ((value != null))
					{
						value.prestamos.Add(this);
						this._codejemplar = value.codejemplar;
					}
					else
					{
						this._codejemplar = default(Nullable<int>);
					}
					this.SendPropertyChanged("ejemplares");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumnos_prestamos", Storage="_alumnos", ThisKey="codalumno", OtherKey="codalumno", IsForeignKey=true)]
		public alumnos alumnos
		{
			get
			{
				return this._alumnos.Entity;
			}
			set
			{
				alumnos previousValue = this._alumnos.Entity;
				if (((previousValue != value) 
							|| (this._alumnos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alumnos.Entity = null;
						previousValue.prestamos.Remove(this);
					}
					this._alumnos.Entity = value;
					if ((value != null))
					{
						value.prestamos.Add(this);
						this._codalumno = value.codalumno;
					}
					else
					{
						this._codalumno = default(string);
					}
					this.SendPropertyChanged("alumnos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.libros")]
	public partial class libros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codlibro;
		
		private string _titulo;
		
		private System.Nullable<int> _codtema;
		
		private System.Nullable<int> _codeditorial;
		
		private System.Nullable<int> _codidioma;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _year;
		
		private char _donado;
		
		private EntitySet<ejemplares> _ejemplares;
		
		private EntityRef<tematicas> _tematicas;
		
		private EntityRef<idiomas> _idiomas;
		
		private EntityRef<editoriales> _editoriales;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodlibroChanging(int value);
    partial void OncodlibroChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OncodtemaChanging(System.Nullable<int> value);
    partial void OncodtemaChanged();
    partial void OncodeditorialChanging(System.Nullable<int> value);
    partial void OncodeditorialChanged();
    partial void OncodidiomaChanging(System.Nullable<int> value);
    partial void OncodidiomaChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OndonadoChanging(char value);
    partial void OndonadoChanged();
    #endregion
		
		public libros()
		{
			this._ejemplares = new EntitySet<ejemplares>(new Action<ejemplares>(this.attach_ejemplares), new Action<ejemplares>(this.detach_ejemplares));
			this._tematicas = default(EntityRef<tematicas>);
			this._idiomas = default(EntityRef<idiomas>);
			this._editoriales = default(EntityRef<editoriales>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codlibro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codlibro
		{
			get
			{
				return this._codlibro;
			}
			set
			{
				if ((this._codlibro != value))
				{
					this.OncodlibroChanging(value);
					this.SendPropertyChanging();
					this._codlibro = value;
					this.SendPropertyChanged("codlibro");
					this.OncodlibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(150)")]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codtema", DbType="Int")]
		public System.Nullable<int> codtema
		{
			get
			{
				return this._codtema;
			}
			set
			{
				if ((this._codtema != value))
				{
					if (this._tematicas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodtemaChanging(value);
					this.SendPropertyChanging();
					this._codtema = value;
					this.SendPropertyChanged("codtema");
					this.OncodtemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeditorial", DbType="Int")]
		public System.Nullable<int> codeditorial
		{
			get
			{
				return this._codeditorial;
			}
			set
			{
				if ((this._codeditorial != value))
				{
					if (this._editoriales.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodeditorialChanging(value);
					this.SendPropertyChanging();
					this._codeditorial = value;
					this.SendPropertyChanged("codeditorial");
					this.OncodeditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codidioma", DbType="Int")]
		public System.Nullable<int> codidioma
		{
			get
			{
				return this._codidioma;
			}
			set
			{
				if ((this._codidioma != value))
				{
					if (this._idiomas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodidiomaChanging(value);
					this.SendPropertyChanging();
					this._codidioma = value;
					this.SendPropertyChanged("codidioma");
					this.OncodidiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donado", DbType="Char(1)")]
		public char donado
		{
			get
			{
				return this._donado;
			}
			set
			{
				if ((this._donado != value))
				{
					this.OndonadoChanging(value);
					this.SendPropertyChanging();
					this._donado = value;
					this.SendPropertyChanged("donado");
					this.OndonadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="libros_ejemplares", Storage="_ejemplares", ThisKey="codlibro", OtherKey="codlibro")]
		public EntitySet<ejemplares> ejemplares
		{
			get
			{
				return this._ejemplares;
			}
			set
			{
				this._ejemplares.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tematicas_libros", Storage="_tematicas", ThisKey="codtema", OtherKey="codtema", IsForeignKey=true)]
		public tematicas tematicas
		{
			get
			{
				return this._tematicas.Entity;
			}
			set
			{
				tematicas previousValue = this._tematicas.Entity;
				if (((previousValue != value) 
							|| (this._tematicas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tematicas.Entity = null;
						previousValue.libros.Remove(this);
					}
					this._tematicas.Entity = value;
					if ((value != null))
					{
						value.libros.Add(this);
						this._codtema = value.codtema;
					}
					else
					{
						this._codtema = default(Nullable<int>);
					}
					this.SendPropertyChanged("tematicas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="idiomas_libros", Storage="_idiomas", ThisKey="codidioma", OtherKey="codidioma", IsForeignKey=true)]
		public idiomas idiomas
		{
			get
			{
				return this._idiomas.Entity;
			}
			set
			{
				idiomas previousValue = this._idiomas.Entity;
				if (((previousValue != value) 
							|| (this._idiomas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._idiomas.Entity = null;
						previousValue.libros.Remove(this);
					}
					this._idiomas.Entity = value;
					if ((value != null))
					{
						value.libros.Add(this);
						this._codidioma = value.codidioma;
					}
					else
					{
						this._codidioma = default(Nullable<int>);
					}
					this.SendPropertyChanged("idiomas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="editoriales_libros", Storage="_editoriales", ThisKey="codeditorial", OtherKey="codeditorial", IsForeignKey=true)]
		public editoriales editoriales
		{
			get
			{
				return this._editoriales.Entity;
			}
			set
			{
				editoriales previousValue = this._editoriales.Entity;
				if (((previousValue != value) 
							|| (this._editoriales.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._editoriales.Entity = null;
						previousValue.libros.Remove(this);
					}
					this._editoriales.Entity = value;
					if ((value != null))
					{
						value.libros.Add(this);
						this._codeditorial = value.codeditorial;
					}
					else
					{
						this._codeditorial = default(Nullable<int>);
					}
					this.SendPropertyChanged("editoriales");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ejemplares(ejemplares entity)
		{
			this.SendPropertyChanging();
			entity.libros = this;
		}
		
		private void detach_ejemplares(ejemplares entity)
		{
			this.SendPropertyChanging();
			entity.libros = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.idiomas")]
	public partial class idiomas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codidioma;
		
		private string _idioma;
		
		private EntitySet<libros> _libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodidiomaChanging(int value);
    partial void OncodidiomaChanged();
    partial void OnidiomaChanging(string value);
    partial void OnidiomaChanged();
    #endregion
		
		public idiomas()
		{
			this._libros = new EntitySet<libros>(new Action<libros>(this.attach_libros), new Action<libros>(this.detach_libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codidioma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codidioma
		{
			get
			{
				return this._codidioma;
			}
			set
			{
				if ((this._codidioma != value))
				{
					this.OncodidiomaChanging(value);
					this.SendPropertyChanging();
					this._codidioma = value;
					this.SendPropertyChanged("codidioma");
					this.OncodidiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idioma", DbType="VarChar(40)")]
		public string idioma
		{
			get
			{
				return this._idioma;
			}
			set
			{
				if ((this._idioma != value))
				{
					this.OnidiomaChanging(value);
					this.SendPropertyChanging();
					this._idioma = value;
					this.SendPropertyChanged("idioma");
					this.OnidiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="idiomas_libros", Storage="_libros", ThisKey="codidioma", OtherKey="codidioma")]
		public EntitySet<libros> libros
		{
			get
			{
				return this._libros;
			}
			set
			{
				this._libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.idiomas = this;
		}
		
		private void detach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.idiomas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.estados")]
	public partial class estados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codestado;
		
		private string _estado;
		
		private EntitySet<ejemplares> _ejemplares;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodestadoChanging(int value);
    partial void OncodestadoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public estados()
		{
			this._ejemplares = new EntitySet<ejemplares>(new Action<ejemplares>(this.attach_ejemplares), new Action<ejemplares>(this.detach_ejemplares));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codestado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codestado
		{
			get
			{
				return this._codestado;
			}
			set
			{
				if ((this._codestado != value))
				{
					this.OncodestadoChanging(value);
					this.SendPropertyChanging();
					this._codestado = value;
					this.SendPropertyChanged("codestado");
					this.OncodestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(30)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estados_ejemplares", Storage="_ejemplares", ThisKey="codestado", OtherKey="codestado")]
		public EntitySet<ejemplares> ejemplares
		{
			get
			{
				return this._ejemplares;
			}
			set
			{
				this._ejemplares.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ejemplares(ejemplares entity)
		{
			this.SendPropertyChanging();
			entity.estados = this;
		}
		
		private void detach_ejemplares(ejemplares entity)
		{
			this.SendPropertyChanging();
			entity.estados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ejemplares")]
	public partial class ejemplares : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codejemplar;
		
		private System.Nullable<int> _codestado;
		
		private System.Nullable<int> _codlibro;
		
		private EntitySet<prestamos> _prestamos;
		
		private EntityRef<estados> _estados;
		
		private EntityRef<libros> _libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodejemplarChanging(int value);
    partial void OncodejemplarChanged();
    partial void OncodestadoChanging(System.Nullable<int> value);
    partial void OncodestadoChanged();
    partial void OncodlibroChanging(System.Nullable<int> value);
    partial void OncodlibroChanged();
    #endregion
		
		public ejemplares()
		{
			this._prestamos = new EntitySet<prestamos>(new Action<prestamos>(this.attach_prestamos), new Action<prestamos>(this.detach_prestamos));
			this._estados = default(EntityRef<estados>);
			this._libros = default(EntityRef<libros>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codejemplar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codejemplar
		{
			get
			{
				return this._codejemplar;
			}
			set
			{
				if ((this._codejemplar != value))
				{
					this.OncodejemplarChanging(value);
					this.SendPropertyChanging();
					this._codejemplar = value;
					this.SendPropertyChanged("codejemplar");
					this.OncodejemplarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codestado", DbType="Int")]
		public System.Nullable<int> codestado
		{
			get
			{
				return this._codestado;
			}
			set
			{
				if ((this._codestado != value))
				{
					if (this._estados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodestadoChanging(value);
					this.SendPropertyChanging();
					this._codestado = value;
					this.SendPropertyChanged("codestado");
					this.OncodestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codlibro", DbType="Int")]
		public System.Nullable<int> codlibro
		{
			get
			{
				return this._codlibro;
			}
			set
			{
				if ((this._codlibro != value))
				{
					if (this._libros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodlibroChanging(value);
					this.SendPropertyChanging();
					this._codlibro = value;
					this.SendPropertyChanged("codlibro");
					this.OncodlibroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ejemplares_prestamos", Storage="_prestamos", ThisKey="codejemplar", OtherKey="codejemplar")]
		public EntitySet<prestamos> prestamos
		{
			get
			{
				return this._prestamos;
			}
			set
			{
				this._prestamos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estados_ejemplares", Storage="_estados", ThisKey="codestado", OtherKey="codestado", IsForeignKey=true)]
		public estados estados
		{
			get
			{
				return this._estados.Entity;
			}
			set
			{
				estados previousValue = this._estados.Entity;
				if (((previousValue != value) 
							|| (this._estados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._estados.Entity = null;
						previousValue.ejemplares.Remove(this);
					}
					this._estados.Entity = value;
					if ((value != null))
					{
						value.ejemplares.Add(this);
						this._codestado = value.codestado;
					}
					else
					{
						this._codestado = default(Nullable<int>);
					}
					this.SendPropertyChanged("estados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="libros_ejemplares", Storage="_libros", ThisKey="codlibro", OtherKey="codlibro", IsForeignKey=true)]
		public libros libros
		{
			get
			{
				return this._libros.Entity;
			}
			set
			{
				libros previousValue = this._libros.Entity;
				if (((previousValue != value) 
							|| (this._libros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._libros.Entity = null;
						previousValue.ejemplares.Remove(this);
					}
					this._libros.Entity = value;
					if ((value != null))
					{
						value.ejemplares.Add(this);
						this._codlibro = value.codlibro;
					}
					else
					{
						this._codlibro = default(Nullable<int>);
					}
					this.SendPropertyChanged("libros");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_prestamos(prestamos entity)
		{
			this.SendPropertyChanging();
			entity.ejemplares = this;
		}
		
		private void detach_prestamos(prestamos entity)
		{
			this.SendPropertyChanging();
			entity.ejemplares = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.editoriales")]
	public partial class editoriales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codeditorial;
		
		private string _editorial;
		
		private EntitySet<libros> _libros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeditorialChanging(int value);
    partial void OncodeditorialChanged();
    partial void OneditorialChanging(string value);
    partial void OneditorialChanged();
    #endregion
		
		public editoriales()
		{
			this._libros = new EntitySet<libros>(new Action<libros>(this.attach_libros), new Action<libros>(this.detach_libros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeditorial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codeditorial
		{
			get
			{
				return this._codeditorial;
			}
			set
			{
				if ((this._codeditorial != value))
				{
					this.OncodeditorialChanging(value);
					this.SendPropertyChanging();
					this._codeditorial = value;
					this.SendPropertyChanged("codeditorial");
					this.OncodeditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editorial", DbType="VarChar(50)")]
		public string editorial
		{
			get
			{
				return this._editorial;
			}
			set
			{
				if ((this._editorial != value))
				{
					this.OneditorialChanging(value);
					this.SendPropertyChanging();
					this._editorial = value;
					this.SendPropertyChanged("editorial");
					this.OneditorialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="editoriales_libros", Storage="_libros", ThisKey="codeditorial", OtherKey="codeditorial")]
		public EntitySet<libros> libros
		{
			get
			{
				return this._libros;
			}
			set
			{
				this._libros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.editoriales = this;
		}
		
		private void detach_libros(libros entity)
		{
			this.SendPropertyChanging();
			entity.editoriales = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.autores")]
	public partial class autores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codautor;
		
		private string _autor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodautorChanging(int value);
    partial void OncodautorChanged();
    partial void OnautorChanging(string value);
    partial void OnautorChanged();
    #endregion
		
		public autores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codautor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codautor
		{
			get
			{
				return this._codautor;
			}
			set
			{
				if ((this._codautor != value))
				{
					this.OncodautorChanging(value);
					this.SendPropertyChanging();
					this._codautor = value;
					this.SendPropertyChanged("codautor");
					this.OncodautorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autor", DbType="VarChar(50)")]
		public string autor
		{
			get
			{
				return this._autor;
			}
			set
			{
				if ((this._autor != value))
				{
					this.OnautorChanging(value);
					this.SendPropertyChanging();
					this._autor = value;
					this.SendPropertyChanged("autor");
					this.OnautorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumnos")]
	public partial class alumnos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _codalumno;
		
		private string _nombre;
		
		private string _telefono;
		
		private System.Nullable<int> _numPrestados;
		
		private EntitySet<prestamos> _prestamos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodalumnoChanging(string value);
    partial void OncodalumnoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnnumPrestadosChanging(System.Nullable<int> value);
    partial void OnnumPrestadosChanged();
    #endregion
		
		public alumnos()
		{
			this._prestamos = new EntitySet<prestamos>(new Action<prestamos>(this.attach_prestamos), new Action<prestamos>(this.detach_prestamos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codalumno", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string codalumno
		{
			get
			{
				return this._codalumno;
			}
			set
			{
				if ((this._codalumno != value))
				{
					this.OncodalumnoChanging(value);
					this.SendPropertyChanging();
					this._codalumno = value;
					this.SendPropertyChanged("codalumno");
					this.OncodalumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(9)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPrestados", DbType="Int")]
		public System.Nullable<int> numPrestados
		{
			get
			{
				return this._numPrestados;
			}
			set
			{
				if ((this._numPrestados != value))
				{
					this.OnnumPrestadosChanging(value);
					this.SendPropertyChanging();
					this._numPrestados = value;
					this.SendPropertyChanged("numPrestados");
					this.OnnumPrestadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="alumnos_prestamos", Storage="_prestamos", ThisKey="codalumno", OtherKey="codalumno")]
		public EntitySet<prestamos> prestamos
		{
			get
			{
				return this._prestamos;
			}
			set
			{
				this._prestamos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_prestamos(prestamos entity)
		{
			this.SendPropertyChanging();
			entity.alumnos = this;
		}
		
		private void detach_prestamos(prestamos entity)
		{
			this.SendPropertyChanging();
			entity.alumnos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.autorexlibro")]
	public partial class autorexlibro
	{
		
		private System.Nullable<int> _codlibro;
		
		private System.Nullable<int> _codautor;
		
		private int _autorxlibro;
		
		public autorexlibro()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codlibro", DbType="Int")]
		public System.Nullable<int> codlibro
		{
			get
			{
				return this._codlibro;
			}
			set
			{
				if ((this._codlibro != value))
				{
					this._codlibro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codautor", DbType="Int")]
		public System.Nullable<int> codautor
		{
			get
			{
				return this._codautor;
			}
			set
			{
				if ((this._codautor != value))
				{
					this._codautor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autorxlibro", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int autorxlibro
		{
			get
			{
				return this._autorxlibro;
			}
			set
			{
				if ((this._autorxlibro != value))
				{
					this._autorxlibro = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaxAutores")]
	public partial class VistaxAutores
	{
		
		private string _autor;
		
		private string _titulo;
		
		public VistaxAutores()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_autor", DbType="VarChar(50)")]
		public string autor
		{
			get
			{
				return this._autor;
			}
			set
			{
				if ((this._autor != value))
				{
					this._autor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(150)")]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this._titulo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
